---
- name: ufw
  hosts: localhost
  tasks:
  - name: Install the latest version of ufw package
    package:
      name: ufw
      state: present
  - name: Ensure the ufw package is running
    service:
      name: ufw
      enabled: yes
      state: started
