---
- name: ufw
  hosts: localhost
  tasks:
  - name: Ensure ufw is at the latest version
    apt:
      name: ufw
      state: latest

---
- name: ufw
  hosts: localhost
  tasks:
  - name: Ensure ufw is at the latest version
    yum:
      name: ufw
      state: latest

---
- name: ufw
  hosts: localhost
  tasks:
  - name: Ensure ufw is at the latest version
    pacman:
      name: ufw
      state: latest
