---
- name: ufw
  hosts: localhost
  tasks:
  - name: Ensure ufw is at the latest version
    package:
      name: ufw
      state: latest
  - name: Ensure ufw is running
    service:
      name: ufw
      state: started
